INSERT INTO Sucursales values ('Sucursal Centro', 'Centro');
INSERT INTO PuntosDeVenta values (15, 1);
INSERT INTO Rubros VALUES ('Zapatillas');
INSERT INTO Rubros VALUES ('Pantalones');
INSERT INTO Rubros VALUES ('Gorras');
INSERT INTO Rubros VALUES ('Camisas');
INSERT INTO Rubros VALUES ('Remeras');
INSERT INTO Marcas VALUES ('Adidas');
INSERT INTO Marcas VALUES ('Nike');
INSERT INTO Marcas VALUES ('Polo');
INSERT INTO Marcas VALUES ('Riders');
INSERT INTO Marcas VALUES ('Lee');
INSERT INTO Marcas VALUES ('Pumas');
INSERT INTO Productos VALUES (1351232, 'Zapatillas Adidas', 10000, 20, 21, 1, 1);
INSERT INTO Productos VALUES (1351233, 'Zapatillas Nike', 10000, 20, 21, 2, 1);
INSERT INTO Productos VALUES (1351234, 'Zapatillas Pumas', 10000, 20, 21, 6, 1);
INSERT INTO Users VALUES ('admin', 1, 'admin@user.com', 'pass');
INSERT INTO Users VALUES ('user1', 0, 'user1@user.com', 'pass');
INSERT INTO Empleados VALUES ('Juan Perez', 'user1', 1);
INSERT INTO TiposDeFactura VALUES ('Factura A', 1);
INSERT INTO CLIENTES VALUES (20000000000, 'Consumidor Final', 'calle 13', 1, 'Consumidor Final', '0800-444-5555');
